from pydantic import BaseModel, Field
from typing import TypedDict, Annotated
from dataclasses import dataclass
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


@dataclass
class Article:
    """
    Represents the details extracted from one news article.

    Attributes:
        source: The news outlet of from which article is extracted from.
        title: Title of news article.
        published_date: Published date of article in ISO format YYYY-MM-DDTHH:MM:SS<timezone>.
        link: Url link to article.
        content: Text content of news article.
    """

    source: str
    title: str
    published_date: str
    link: str
    content: str


class ArticleSummary(BaseModel):
    """
    Represents the summary of one news article.

    Attributes:
        title: Title of news article.
        content: Summary of the news article.
    """

    model_config = {"frozen": True}  # makes the model immutable + hashable

    title: str = Field(description="Title of the news article as extracted from data.")
    content: str = Field(
        description="A paragraph of up to 5 sentences for the summary of the news article, containing key information."
    )


class ArticleSummaryList(BaseModel):
    """
    Represents the list containing the summary of each of the selected news article.
    This is required since structured output cannot take in list as input.
    Pydantic checks before passing to vector database to store the generated summaries.
    """

    articles: list[ArticleSummary]


class Feedback(BaseModel):
    """
    Represents the feedback of one news summary generated by the summary generator.
    Evaluate the summary based on different metrics and provide comments to correct the mistakes.
    The metrics cover the elements that make a good summary:
    - factual accuracy of content (trust-worthiness of summary)
    - completeness of summary (all information of news is captured)
    - clarity of summary (understandable for reader)

    Attributes:
        title: Title of news article.
        grounded_title: Whether title matches exactly that of source article.
        grounded_content: Whether content is based on source article and there is no additional information/hallucination.
        relevant: Whether the news article covers financial topics.
        completeness: Whether content covers all key information in news article.
        clarity: Score between 1 to 5 on how understandable the summary is.
        comments: Any feedback on the summary, can be suggestions to improve or validation note.
    """

    title: str = Field(
        ..., description="Title of the news article that is being summarized"
    )
    grounded_title: bool = Field(
        ..., description="True if summary title matches exactly the source article"
    )
    grounded_content: bool = Field(
        ...,
        description="True if every claim in summary is traceable to the source article",
    )
    relevant: bool = Field(
        ..., description="True if content of summary is related to finance or markets"
    )
    completeness: bool = Field(
        ...,
        description="True if the summary covers all key information in the source article",
    )
    clarity: int = Field(
        ...,
        ge=1,
        le=5,
        description="To what extent the summary is concise and can be understood without ambiguity. 5 is the best.",
    )
    comments: str = Field(
        ...,
        description="Actionable feedback for improvement, or an approval statement if the summary is satisfactory.",
    )

    # @field_validator("clarity", mode="before")
    # @classmethod
    # def coerce_clarity(cls, v):
    #     """
    #     Convert to integer between 1 to 5 before pydantic checks.
    #     """
    #     try:
    #         v = int(v)
    #     except (TypeError, ValueError):
    #         return 3

    #     if v < 1:
    #         return 1  # clamp to lower bound
    #     if v > 5:
    #         return 5  # clamp to upper bound
    #     return v


@dataclass
class EvaluationResult:
    """
    Represents the output after evaluating one generated summary.

    Attributes:
        feedback: Metric scores and comments after evaluating the summary as Feedback object.
        messages: System and input prompt for the LLM to do the evaluation.
    """

    feedback: Feedback
    messages: list[AnyMessage]


class SharedState(TypedDict):
    """
    Shared state that is accessible across all nodes in the graph.
    All variables are rewritten by nodes since previous states like
    past summaries/feedback does not affect each node.

    Only messages is not rewritten but appended to track LLM calls.

    Attributes:
        messages: List of system and user prompts of type AnyMessage used in all LLM in graph.
        gathered_data: List of Articles extracted from the RSS feed url.
        past_summaries:  List of past ArticleSummary that has similar content as any of the Articles in gathered_data.
        current_summary: List of ArticleSummary of importance news generated by the generator LLM from gathered_data.
        critic_feedback: List of Feedback, one for each ArticleSummary in current_summary generated from the critic LLM.
        approved: Approval status of the generated summaries in boolean type.
        critic_count: Number of times feedback was given for the generated summaries.
    """

    # store all messages from LLM calls
    # reducer function `add_messages` to append message (without duplicates) instead of rewriting
    messages: Annotated[list[AnyMessage], add_messages]
    gathered_data: list[Article]
    past_summaries: list[ArticleSummary]
    current_summary: list[ArticleSummary]
    critic_feedback: list[Feedback]
    approved: bool
    critic_count: int  # track to prevent infinite loop
