from omegaconf import DictConfig
import chromadb
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
from chromadb.utils import embedding_functions
import logging

from src.utils.logging import setup_logging
from src.state_and_dataclass import SharedState, ArticleSummary

setup_logging()
logger = logging.getLogger("function_node")


class SummaryDatabase:
    """
    ChromaDB vector database that stores all summaries generated.
    Provide the function to add ArticleSummary into the vector database.
    Provide the function to extract past summaries that have similar content as the newly extracted news articles.
    """

    def __init__(self, cfg: DictConfig) -> None:
        """
        Set up the ChromaDB vector database with a persistent storage to save all the documents.
        Create a collection to store all the document and specify the embedding function.

        Args:
            cfg: Configurations of the vector database to use to store past summaries.
        """
        self.timezone = ZoneInfo(cfg["timezone"])
        # create client to save data to local disk at the specified directory path for persistent storage
        self.client = chromadb.PersistentClient(path=cfg["storage_path"])

        # set embedding for the vector database, default embedding is "all-MiniLM-L6-v2"
        self.embedding_fn = embedding_functions.SentenceTransformerEmbeddingFunction(
            model_name=cfg["embedding_model"]
        )

        # set collection name to store all summary
        self.collection_name = cfg["collection_name"]
        self.lookback_days = cfg["lookback_days"]
        self.similarity_threshold = cfg["similarity_threshold"]

        # set the collection or create it if does not exist
        self.set_collection()

        logger.info("Summary database set up.")

    def set_collection(self) -> None:
        """
        Set the collection to contain all the generated news summaries.
        Set the distance in Hierarchical Navigable Small World (indexing algorithm)
        to be cosine similarity distance for semantic similarity between text.
        """
        self.collection = self.client.get_or_create_collection(
            name=self.collection_name,
            embedding_function=self.embedding_fn,
            metadata={"hnsw:space": "cosine"},
        )

    def empty_data_in_collection(self) -> None:
        """
        Empty all the data in the collection by first deleting the collection and recreating it.
        """
        # delete the collection
        self.client.delete_collection(name=self.collection_name)

        self.set_collection()

        logger.info(
            f"Emptied the database, the number of items in database is: {self.collection.count()}"
        )

    def add_summaries(self, state: SharedState) -> None:
        """
        Add summaries generated by LLM stored in the `current_summary` field in state into the database.
        Store each summary separately so that similarity score with articles will not be diluted.

        Each summary has id, document and metadata.
        Metadata has the input date of summary both in string and integer format.
        id is of the format `Article_{i}_{current_datetime_string}.

        Args:
            state: Common graph state across the graph.
        """
        logger.info(f"Current database size is: {self.collection.count()}")
        # get summary generated
        article_summaries = state.get("current_summary")

        # data for each article summary
        ids, documents, metadatas = [], [], []

        # get storage datetime and date
        current_datetime = datetime.now(self.timezone)
        summary_date = current_datetime.date().isoformat()
        current_datetime_string = current_datetime.isoformat()

        # store each summary separately
        for i, summary in enumerate(article_summaries):
            # Combine title and summary as one document
            combined_text = f"{summary.title}\n{summary.content}"
            documents.append(combined_text)

            # id is storage time and article number
            article_id = f"Article_{i}_{current_datetime_string}"
            ids.append(article_id)

            # add date in string and in integer as metadata
            metadatas.append(
                {"date": summary_date, "date_int": current_datetime.date().toordinal()}
            )

        # add all
        self.collection.add(ids=ids, documents=documents, metadatas=metadatas)
        logger.info(
            f"Added current summaries into summary database, updated database size is: {self.collection.count()}"
        )

    def query_similar_summaries(
        self, state: SharedState
    ) -> dict[str, list[ArticleSummary]]:
        """
        Extract out any previously generated summaries in the summmary database that are similar
        to any of the current news articles extracted.

        Only search among past summaries that are within a lookback range from current date since
        summaries that are older are unlikely to contain similar contents as current news article.

        Calculate similarity score between each pair of news article and past summary,
        and if it exceeds a threshold, the past summary is extracted out.
        Pairwise calculation prevents dilution of similarity score when there is large number
        of articles extracted, ensuring correct extraction of past summaries.

        Args:
            state: Common graph state across the graph.

        Returns:
            Updated `past_summaries` field in the shared state, which can be empty list if no matching summaries.
        """

        # if collection is empty, return empty list
        if self.collection.count() == 0:
            logger.info("Returned empty list as collection is empty")
            return {"past_summaries": []}

        # search among past summaries that is within lookback range (past few days)
        # since older summaries unlikely to have similar content
        # if that subset collection is empty, return empty list
        current_date = datetime.now(self.timezone).date()

        # convert date to number for comparison that is used in filtering the search
        lookback_start_range = (
            current_date - timedelta(days=self.lookback_days)
        ).toordinal()

        logger.info(f"lookback range is from {lookback_start_range}")

        # set the date filter to query the collection, to be greater than the lookback start range
        filter_dict = {"date_int": {"$gte": lookback_start_range}}

        collection_to_search = self.collection.get(where=filter_dict)
        collection_size = len(collection_to_search["ids"])

        if collection_size == 0:
            logger.info("Returned empty list as subset collection is empty")
            return {"past_summaries": []}

        # get the current news articles gathered
        news_articles_gathered = state.get("gathered_data")

        # list to hold all previous summaries with similar content as current articles
        related_past_summaries = []

        # calculate for each pair
        for article in news_articles_gathered:
            # get semantic similarity score of article title+content with past summaries
            # if n_result larger than subset of collection, error will occur
            results = self.collection.query(
                query_texts=[f"{article.title}\n{article.content}"],
                n_results=collection_size,  # return all queries, default is 10
                where=filter_dict,
            )

            # Filter for past summaries that exceed similarity threshold
            for doc, dist in zip(
                results["documents"][0],
                results["distances"][0],
            ):
                # similarity score = 1 - cosine distance
                similarity_score = 1 - dist
                if similarity_score >= self.similarity_threshold:
                    # document is title\n content
                    split_doc = doc.split("\n")
                    related_past_summaries.append(
                        ArticleSummary(title=split_doc[0], content=split_doc[1])
                    )
                    logger.info(
                        f"Adding to past summaries article: {split_doc[0]} for score: {similarity_score:.3f}"
                    )

        # reduce the list to only unique summmaries
        # can be empty if no past summaries exceed threshold
        return {"past_summaries": list(set(related_past_summaries))}


# import hydra
# from src.node.state_and_dataclass import Article
# @hydra.main(config_path="../../config", config_name="config", version_base=None)
# def main(cfg: DictConfig) -> None:
#     # get the configurations
#     database_cfg = cfg.database
#     print("database cfg")
#     print(database_cfg)
#     summary_database = SummaryDatabase(database_cfg)

#     summary_database.empty_data_in_collection()
#     content = """
#     MANILA, June 22 : Growth in the Philippines this year will be lower than previously forecast due to the energy crisis and the lingering effects of a corruption scandal that has slowed government spending, the economic planning secretary said on Monday.

#     Growth is now seen coming in at 3.5 per cent to 4.5 per cent this year, below the government’s already lowered forecast of 5.0 per cent to 6.0 per cent, Balisacan said in an interview with One News.

#     He said the cut reflected slower spending in the aftermath of corruption allegations related to flood control projects and rising inflation driven by higher global oil prices.

#     The economy grew 2.8 per cent in the first quarter from a year earlier, lower than forecast.
#     The central bank raised rates for a second straight meeting last week, a move Balisacan said was justified to ensure elevated inflation does not become persistent.
#     While annual inflation eased to 6.8 per cent in May from 7.2 per cent a month earlier, it remained well above the central bank's 3.0 per cent target.
#     Balisacan said a government inter-agency panel responsible for setting medium-term fiscal and economic goals had met recently to review the targets, and the outcome will be released soon.
#     """
#     # add summary
#     initial_state: SharedState = {
#         "gathered_data": [Article(source="source", title="Philippines cuts forecast agains.", published_date="date", link="www.test.com", content=content)],
#         "past_summaries": [],
#         "current_summary": [ArticleSummary(title="Philippines cuts 2026 growth forecast", content="The Philippines’ economic growth forecast has been downgraded to 5.0 percent for this year due to an energy crisis and reduced government spending.")],
#     }

#     print(f"before adding data: {summary_database.collection.count()}")

#     summary_database.add_summaries(initial_state)

#     print(f"after adding data: {summary_database.collection.get()}")

#     similar_summary = summary_database.query_similar_summaries(initial_state)

#     print(f"similar_summary is {similar_summary}")


# if __name__ == "__main__":
#     main()
