from pydantic import BaseModel, Field
from typing import List, TypedDict, Optional
from dataclasses import dataclass


@dataclass
class Article:
    """
    Represents the details extracted from one news article.

    Attributes:
        source: The news outlet of from which article is extracted from.
        title: Title of news article.
        published_date: Published date of article in ISO format YYYY-MM-DDTHH:MM:SS<timezone>.
        link: Url link to article.
        content: Text content of news article.
    """

    source: str
    title: str
    published_date: str
    link: str
    content: str


class ArticleSummary(BaseModel):
    """
    Represents the summary of one news article.

    Attributes:
        title: Title of news article.
        content: Summary of the news article.
    """

    model_config = {"frozen": True}  # makes the model immutable + hashable

    title: str = Field(description="Title of the news article as extracted from data.")
    content: str = Field(
        description="A paragraph of up to 5 sentences for the summary of the news article, containing key information."
    )


class ArticleSummaryList(BaseModel):
    articles: List[ArticleSummary]


class SharedState(TypedDict):
    """
    Shared state across all nodes in the graph.

    Attributes:
        gathered_data: List of Articles extracted from the RSS feed url.
        past_summaries:  List of past ArticleSummary that has similar content as any of the Articles in gathered_data.
        current_summary: List of ArticleSummary of importance news generated by the LLM from gathered_data.
    """

    # messages: Annotated[List[AnyMessage], add_messages]
    gathered_data: List[Article]
    past_summaries: Optional[List[ArticleSummary]]  # can be empty
    current_summary: List[ArticleSummary]
    # approved: bool
    # feedback_list: Annotated[List[str], operator.add]
    # rewrite_count: int
