from pydantic import BaseModel, Field
from typing import List, TypedDict, Annotated
from dataclasses import dataclass
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages


@dataclass
class Article:
    """
    Represents the details extracted from one news article.

    Attributes:
        source: The news outlet of from which article is extracted from.
        title: Title of news article.
        published_date: Published date of article in ISO format YYYY-MM-DDTHH:MM:SS<timezone>.
        link: Url link to article.
        content: Text content of news article.
    """

    source: str
    title: str
    published_date: str
    link: str
    content: str


class ArticleSummary(BaseModel):
    """
    Represents the summary of one news article.

    Attributes:
        title: Title of news article.
        content: Summary of the news article.
    """

    model_config = {"frozen": True}  # makes the model immutable + hashable

    title: str = Field(description="Title of the news article as extracted from data.")
    content: str = Field(
        description="A paragraph of up to 5 sentences for the summary of the news article, containing key information."
    )


class ArticleSummaryList(BaseModel):
    """
    Represents the list containing the summary of each of the selected news article.
    This is required since structured output cannot take in list as input.
    Pydantic checks before passing to vector database to store the generated summaries.
    """

    articles: List[ArticleSummary]


class Feedback(BaseModel):
    """
    Represents the feedback of one news summary generated by the summary generator.

    Attributes:
        title: Title of news article.
        grounded: Whether the summary is based on article text or there is hallucinations.
        relevant: Whether the news article covers financial topics.
        clarity: Score to rate how understandable the summary is.
        comments: Any feedback on the summary, can be suggestions to improve or validation note.
    """

    title: str = Field(
        ..., description="Title of the news article that is being summarized"
    )
    grounded: bool = Field(
        ..., description="True if every claim is traceable to the source article"
    )
    relevant: bool = Field(
        ..., description="True if the news article is related to finance or markets"
    )
    clarity: int = Field(
        ...,
        ge=1,
        le=5,
        description="To what extent the summary is concise and can be understood without ambiguity. 5 is the best.",
    )
    comments: str = Field(
        ...,
        description="Actionable feedback for improvement, or an approval statement if the summary is satisfactory.",
    )


class SharedState(TypedDict):
    """
    Shared state across all nodes in the graph.

    Attributes:
        gathered_data: List of Articles extracted from the RSS feed url.
        past_summaries:  List of past ArticleSummary that has similar content as any of the Articles in gathered_data.
        current_summary: List of ArticleSummary of importance news generated by the LLM from gathered_data.
    """

    # store all messages from LLM calls
    # reducer function to append message (without duplicates) instead of rewriting
    messages: Annotated[List[AnyMessage], add_messages]
    gathered_data: List[Article]
    past_summaries: List[ArticleSummary]
    current_summary: List[ArticleSummary]
    # approved: bool
    critic_feedback: List[
        Feedback
    ]  # rewritten since the summary is newly generated and not edited
    # rewrite_count: int
