from omegaconf import DictConfig, OmegaConf
import logging
from langchain_core.messages import AnyMessage, HumanMessage, SystemMessage

from src.utils.logging import setup_logging
from src.utils.llm_helper import get_llm
from src.state_and_dataclass import SharedState, Feedback, EvaluationResult

setup_logging()
logger = logging.getLogger("llm_node")


# no longer using tools since the evaluation just required comparsion between summary and original text (both provided)
# moreover, deciding if summaries is approved uses deterministic algorithm, so no tool call required
class SummaryCritic:
    """
    Use LLM model to provide feedback on each of the summaries generated.

    Each feedback includes metrics to evaluate if a summary is factually accurate,
    covers all information in source and is understandable and comments to
    correct the errors made.

    From the feedback scores, determine whether the summaries are approved
    using a set of criteria to set approval status.
    """

    def __init__(self, cfg: DictConfig) -> None:
        """
        Set the LLM to provide feedback on the summaries generated
        using the configuration file that contains the model arguments.

        LLM will output the feedback as a structured output so that the
        approver helper function can decide on the approval status.

        Args:
            cfg: Configurations for the summary critic LLM.

        Raise:
            ValueError if LLM cannot be initialized when the provider is not in allowed list.
        """
        # get config for the summary critic
        llm_cfg = cfg["critic"]

        # get system prompt
        self.system_prompt = llm_cfg["system_prompt"]

        # get llm provider
        self.provider = llm_cfg["provider"]

        # set the model arguments which must have keys that match the input arguments of model
        self.model_args = OmegaConf.to_container(llm_cfg["model_args"])

        try:
            self.llm = get_llm(self.provider, self.model_args)

            # set the model to output each summary evaluation as Feedback object
            # "json_mode" to faciliate parsing as Feedback
            self.structured_llm = self.llm.with_structured_output(
                Feedback, method="json_mode"
            )
            logger.info("Set the LLM for summary critic.")
        except ValueError as e:
            logger.error(f"Failure to set LLM to provide feedback for summaries: {e}")
            raise

    @staticmethod
    def get_approval_status(feedback_list: list[Feedback]) -> bool:
        """
        Review the feedback from the critic LLM and decide if the summaries generated is approved.

        If at least one of the summaries is inaccurate(title/summary) or
        irrelevant(not about financial news), or incomplete(missing information), set status as False.

        If the average clarity score (perfect score is 5) is less than 2.5, set the status as False.

        Set to True only when the average clarity score is >=2.5 and all summaries are accrate,
        relevant and complete.

        Args:
            feedback_list: List of Feedback object for each summary generated by the
                        critic LLM after reviewing each summary using a set of metrics.

        Returns:
            Boolean value which represents the approval status of the summary generated.
        """

        # at least one title did not match original title
        list_grounded_title = [fb.grounded_title for fb in feedback_list]
        if False in list_grounded_title:
            logger.info(
                "Approval status set to False due to mismatch in summary title."
            )
            return False

        # at least one summary include details beyond original news content
        list_grounded_content = [fb.grounded_content for fb in feedback_list]
        if False in list_grounded_content:
            logger.info(
                "Approval status set to False due to factual inaccuracies in summary content."
            )
            return False

        # at least one summary is not related to finance/market news
        list_relevant = [fb.relevant for fb in feedback_list]
        if False in list_relevant:
            logger.info(
                "Approval status set to False due to irrelevant summary content."
            )
            return False

        # at least one summary contains incomplete information
        list_completeness = [fb.completeness for fb in feedback_list]
        if False in list_completeness:
            logger.info(
                "Approval status set to False due to incompleteness of summary content."
            )
            return False

        # check that summary is clear
        clarity_scores = [fb.clarity for fb in feedback_list]
        avg_score = sum(clarity_scores) / len(clarity_scores)
        if avg_score >= 2.5:
            logger.info(
                "Approval status set to True since all summaries are grounded, relevant, clear and complete."
            )
            return True
        else:
            logger.info(
                "Approval status set to False due to poor clarity of summary content."
            )
            return False

    @staticmethod
    def _create_user_prompt(
        sm_title: str,
        sm_content: str,
        original_article_content: str,
    ) -> str:
        """
        Create user prompt for the critic LLM that it will use to generate a Feedback.

        Args:
            sm_title: The title of the summary.
            sm_content: The content of the summary.
            original_article_content: The orginal full text of the article that matches the summary's title.

        Returns:
            String containing title and content of the summary to be evaluated and the
            orginal full text of the article that the summary is derived from.
        """

        logger.info("Created summary critic user prompt")
        return (
            f"TITLE: {sm_title}\n\n"
            f"ORIGINAL_ARTICLE_CONTENT:\n{original_article_content}\n\n"
            f"DRAFT_SUMMARY:\n{sm_content}"
        )

    def evaluate_one_summary(
        self,
        sm_title: str,
        sm_content: str,
        original_article_content: str,
    ) -> EvaluationResult:
        """
        Use the critic LLM to evaluate the provided summary using the orginal full text of the article
        as ground truth and get feedback on it.

        Return the LLM messages as well in order to update the `messages` field in the graph state.

        Args:
            sm_title: The title of the summary.
            sm_content: The content of the summary.
            original_article_content: The orginal full text of the article that matches the summary's title.

        Returns:
            EvaluationResult that contains:
            - messages: input messages that is used to invoke the LLM
            - feedback: Feedback object that represents the feedback of the LLM on a generated summary.
        """
        # create the user request
        user_prompt = self._create_user_prompt(
            sm_title, sm_content, original_article_content
        )

        # start new conversation for each summary evaluation
        messages: list[AnyMessage] = [
            SystemMessage(content=self.system_prompt),
            HumanMessage(content=user_prompt),
        ]

        # does not return AnyMessage, return type is Feedback due to structured output
        one_feedback = self.structured_llm.invoke(messages)

        logger.info(f"Evaluated summary for article: {sm_title}.")

        # return the messages to append to shared state
        return EvaluationResult(feedback=one_feedback, messages=messages)

    def evaluate_all_summaries(
        self, state: SharedState
    ) -> tuple[list[AnyMessage], list[Feedback]]:
        """
        Get a for loop to evaluate and get feedback for each summary generated.
        If the title of the summary does not match any of the title of the articles extracted,
        directly assign a negative feedback (grounded_title=False).

        If title matches an article, extract the full text of the matched article and
        use `evaluate_one_summary` to get feedback.

        Args:
            state: Common graph state across the graph.

        Returns:
            all_messages: List of LLM messages output from `evaluate_one_summary`.
            all_feedback: List of Feedback object, each for a summary evaluated.
        """
        # get information to evaluate
        current_summary = state.get("current_summary")
        news_articles = state.get("gathered_data")
        all_titles = [article.title for article in news_articles]

        # list to store all feedback and messages
        all_feedback = []
        all_messages = []

        # evaluate each summary
        # first check if title matches any news, if does not match not grounded
        # if match, extract the corresponding article content and evaluate
        for sm in current_summary:
            sm_title = sm.title
            if sm_title not in all_titles:
                logger.info(
                    f"Summary title: {sm_title} not in title list, appended negative feedback"
                )
                # no LLM call, so no logging of messages
                # negative feedback
                fb = Feedback(
                    title=sm_title,
                    grounded_title=False,
                    grounded_content=False,
                    relevant=False,
                    completeness=False,
                    clarity=1,
                    comments="Title did not match any news article.",
                )
            else:
                # use title to get original news article content
                # find first match
                logger.info(
                    f"Summary title: {sm_title} in title list. Doing evaluation of summary."
                )
                matched_article = next(a for a in news_articles if a.title == sm_title)
                original_article_content = matched_article.content
                fb_msg = self.evaluate_one_summary(
                    sm_title, sm.content, original_article_content
                )
                fb = fb_msg.feedback
                all_messages.extend(fb_msg.messages)  # messages is a list

            all_feedback.append(fb)

        # return all messages (all messages from each LLM call) and all feedback
        logger.info("Completed evaluation of all summaries.")
        return all_messages, all_feedback

    def feedback_and_get_approval_status(
        self,
        state: SharedState,
    ) -> dict[str, list[AnyMessage] | list[Feedback] | bool | int]:
        """
        First use `evaluate_all_summaries` to get feedback for all summaries generated.
        Then use `get_approval_status` on the feedback to get the approval status.
        Increase the `critic_count` in the graph state by 1.

        The approval status will determine if the summaries can be sent via email (email node) or
        regeneration of summaries is required (go back to summary generation node).

        Args:
            state: Common graph state across the graph.

        Returns:
            Updated `messages`, `critic_feedback`, `approved` and `critic_count` fields in the shared state.
        """
        logger.info("Starting evaluation of summaries to get approval status...")
        # get all feedback, one for each summary List[Feedback]
        # need to return messages and feedback to update graph state
        all_messages, all_feedback = self.evaluate_all_summaries(state)

        # get critic count
        current_critic_count = state.get("critic_count")

        # boolean
        approval_status = self.get_approval_status(all_feedback)

        # update shared state
        return {
            "messages": all_messages,
            "critic_feedback": all_feedback,
            "approved": approval_status,
            "critic_count": current_critic_count + 1,
        }
